#!/bin/bash

declare local dir=$(dirname $0)

# Template for copying files for root and user
function copy {
  for file in "$@"; do
    cp ${dir}/${file} ~/${file}           # Admin User
    sudo cp ${dir}/${file} /root/${file}  # Root User
  done
}

# Copy the files
copy .bashrc .vimrc

# Cleanup
sudo rm -R ${dir}
